name: c3k
dependencies:
  - python=3.9
  # infrastructure
  - pip
  - ipython
  - pyyaml
  # scientific computing
  - numpy
  - scipy
  - matplotlib
  - h5py
  # astro
  - astropy
  - pip:
    - astro-prospector
    - astro-sedpy

# --- via setup.py ---
# ckc, python-fsps