name: c3k
dependencies:
  # infrastructure
  - ipython
  - pyyaml
  # scientific computing
  - numpy
  - scipy
  - matplotlib
  - h5py
  # astro
  - astropy
  pip:
    - astro-prospector
    - astro-sedpy

# --- via setup.py ---
# ckc, python-fsps